
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testtttt
    username: root
    password: green502

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: on
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
logging:
  level:
    org.hibernate.sql: trace
    org.hibernate.orm.jdbc.bind: trace # ???? ???? ?? ??
